CREATE TABLE User (
    id VARCHAR(255) NOT NULL,
    firstCommentId VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY(id),
    CONSTRAINT FK_2DA179777EB9366D FOREIGN KEY (firstCommentId) REFERENCES Comment (id)
        NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IDX_2DA179777EB9366D ON User (firstCommentId);
CREATE TABLE UserFavoriteComments (
    userId VARCHAR(255) NOT NULL,
    commentId VARCHAR(255) NOT NULL,
    PRIMARY KEY(userId, commentId),
    CONSTRAINT FK_ED301B7A64B64DCC FOREIGN KEY (userId) REFERENCES User (id) ON DELETE CASCADE
        NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT FK_ED301B7A6690C3F5 FOREIGN KEY (commentId) REFERENCES Comment (id) ON DELETE CASCADE
        NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IDX_ED301B7A64B64DCC ON UserFavoriteComments (userId);
CREATE INDEX IDX_ED301B7A6690C3F5 ON UserFavoriteComments (commentId);
CREATE TABLE UserReadComments (
    userId VARCHAR(255) NOT NULL,
    commentId VARCHAR(255) NOT NULL,
    PRIMARY KEY(userId, commentId),
    CONSTRAINT FK_96EFAC6364B64DCC FOREIGN KEY (userId) REFERENCES User (id) ON DELETE CASCADE
        NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT FK_96EFAC636690C3F5 FOREIGN KEY (commentId) REFERENCES Comment (id) ON DELETE CASCADE
        NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IDX_96EFAC6364B64DCC ON UserReadComments (userId);
CREATE INDEX IDX_96EFAC636690C3F5 ON UserReadComments (commentId);
CREATE TABLE Comment (
    id VARCHAR(255) NOT NULL,
    authorId VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY(id),
    CONSTRAINT FK_5BC96BF0A196F9FD FOREIGN KEY (authorId) REFERENCES User (id)
        NOT DEFERRABLE INITIALLY IMMEDIATE
);
CREATE INDEX IDX_5BC96BF0A196F9FD ON Comment (authorId);
