CREATE TABLE User (
    id VARCHAR(255) NOT NULL,
    firstCommentId VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY(id)
);
CREATE INDEX IDX_2DA179777EB9366D ON User (firstCommentId);
CREATE TABLE UserFavoriteComments (
    UserId VARCHAR(255) NOT NULL,
    CommentId VARCHAR(255) NOT NULL,
    PRIMARY KEY(UserId, CommentId)
);
CREATE INDEX IDX_ED301B7A631A48FA ON UserFavoriteComments (UserId);
CREATE INDEX IDX_ED301B7AE4614156 ON UserFavoriteComments (CommentId);
CREATE TABLE UserReadComments (
    UserId VARCHAR(255) NOT NULL,
    CommentId VARCHAR(255) NOT NULL,
    PRIMARY KEY(UserId, CommentId)
);
CREATE INDEX IDX_96EFAC63631A48FA ON UserReadComments (UserId);
CREATE INDEX IDX_96EFAC63E4614156 ON UserReadComments (CommentId);
CREATE TABLE Comment (
    id VARCHAR(255) NOT NULL,
    authorId VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY(id)
);
CREATE INDEX IDX_5BC96BF0A196F9FD ON Comment (authorId);
