CREATE TABLE User (
    id VARCHAR(255) NOT NULL,
    firstCommentId VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY(id)
);
CREATE INDEX IDX_2DA179777EB9366D ON User (firstCommentId);
CREATE TABLE UserFavoriteComments (
    userId VARCHAR(255) NOT NULL,
    commentId VARCHAR(255) NOT NULL,
    PRIMARY KEY(userId, commentId)
);
CREATE INDEX IDX_ED301B7A64B64DCC ON UserFavoriteComments (userId);
CREATE INDEX IDX_ED301B7A6690C3F5 ON UserFavoriteComments (commentId);
CREATE TABLE UserReadComments (
    userId VARCHAR(255) NOT NULL,
    commentId VARCHAR(255) NOT NULL,
    PRIMARY KEY(userId, commentId)
);
CREATE INDEX IDX_96EFAC6364B64DCC ON UserReadComments (userId);
CREATE INDEX IDX_96EFAC636690C3F5 ON UserReadComments (commentId);
CREATE TABLE Comment (
    id VARCHAR(255) NOT NULL,
    authorId VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY(id)
);
CREATE INDEX IDX_5BC96BF0A196F9FD ON Comment (authorId);
